name=K4_ENC
version=1.0.0
author=Your ronnie
maintainer=ronnie.berzins@gmail.com
sentence=A minimalist and functional rotary encoder library for Arduino R4.
paragraph=This library provides an easy way to read rotary encoders using Pins 2 and 3 by default. It includes built-in non-blocking debouncing for a push button on Pin 4 using millis().
category=Signal Input/Output
url=https://github.com/YOUR_GITHUB_USERNAME/K4_ENC
architectures=renesas_uno
includes=K4_ENC.h